// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfzq3rfEjiD1gY2rfV0ATg1SFknRgv7xw',
    appId: '1:18089528011:web:0c4167b8db505bed51a94e',
    messagingSenderId: '18089528011',
    projectId: 'rankcmpe133',
    authDomain: 'rankcmpe133.firebaseapp.com',
    storageBucket: 'rankcmpe133.appspot.com',
    measurementId: 'G-YCHLH0C1FZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaTAPWnZDJGVQJMMh7ofU40KwfmpPoYyI',
    appId: '1:18089528011:android:d52bd10f6bb5684d51a94e',
    messagingSenderId: '18089528011',
    projectId: 'rankcmpe133',
    storageBucket: 'rankcmpe133.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXCABr0zQBaEO8zt-JJddUubma1tjWcqg',
    appId: '1:18089528011:ios:fe56709da138ec4251a94e',
    messagingSenderId: '18089528011',
    projectId: 'rankcmpe133',
    storageBucket: 'rankcmpe133.appspot.com',
    iosClientId: '18089528011-fuftsr11uousc55svqgvt9qt95vul3ds.apps.googleusercontent.com',
    iosBundleId: 'com.example.rank133',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXCABr0zQBaEO8zt-JJddUubma1tjWcqg',
    appId: '1:18089528011:ios:fe56709da138ec4251a94e',
    messagingSenderId: '18089528011',
    projectId: 'rankcmpe133',
    storageBucket: 'rankcmpe133.appspot.com',
    iosClientId: '18089528011-fuftsr11uousc55svqgvt9qt95vul3ds.apps.googleusercontent.com',
    iosBundleId: 'com.example.rank133',
  );
}
